name: eliuds-eggs

dependencies:
  - base

library:
  exposed-modules: EliudsEggs
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - eliuds-eggs
      - hspec
